"""add legal authority and dispatch guardrails tables

Revision ID: 348c31576db9
Revises: 07098cdf83b6
Create Date: 2026-07-01 19:44:25.364125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '348c31576db9'
down_revision: Union[str, Sequence[str], None] = '07098cdf83b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name_th', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('agency_type', sa.String(length=100), nullable=False),
    sa.Column('parent_agency_id', sa.String(length=100), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.ForeignKeyConstraint(['parent_agency_id'], ['agency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatch_guardrail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_code', sa.String(length=100), nullable=False),
    sa.Column('is_prohibited_without_auth', sa.Boolean(), nullable=False),
    sa.Column('is_allowed_before_approval', sa.Boolean(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_code')
    )
    op.create_table('district_authority_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('authority_provision_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_provision',
    sa.Column('provision_hash', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=200), nullable=False),
    sa.Column('provision_reference', sa.String(length=100), nullable=False),
    sa.Column('authority_type', sa.String(length=100), nullable=False),
    sa.Column('territorial_scope', sa.String(length=100), nullable=False),
    sa.Column('action_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_action_specific_order', sa.Boolean(), nullable=False),
    sa.Column('may_auto_dispatch', sa.Boolean(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.PrimaryKeyConstraint('provision_hash')
    )
    op.create_table('legal_review_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('review_type', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('provision_id', sa.String(length=100), nullable=True),
    sa.Column('review_question', sa.Text(), nullable=False),
    sa.Column('required_reviewer_role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'open'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('legal_review_task')
    op.drop_table('legal_provision')
    op.drop_table('district_authority_candidate')
    op.drop_table('dispatch_guardrail')
    op.drop_table('agency')
    # ### end Alembic commands ###
